//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public int UrlId { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
        public int Hits { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BrandedDomainId { get; set; }
        public System.DateTime RegDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BrandedDomain BrandedDomain { get; set; }
        public virtual Company Company { get; set; }
    }
}
