//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlStat
    {
        public int UrlStatId { get; set; }
        public string UserAgent { get; set; }
        public string IpAddress { get; set; }
        public string UserLanguage { get; set; }
        public string UrlReferer { get; set; }
        public int UrlId { get; set; }
        public string Browser { get; set; }
        public string MajorVersion { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string UserPlatform { get; set; }
        public string UserPlatformVersion { get; set; }
        public string Device { get; set; }
        public string DeviceModel { get; set; }
        public string UrlKey { get; set; }
    }
}
